version: "3.8"

services:
  webapp:
    build:
      context: .
      args:
        migrate: "YES"
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - CONNECTIONSTRING=mongodb://mongo:27017/trainbookings
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.6-focal
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    logging:
      driver: none

volumes:
  mongodb:
  mongodb_config:
