version: "3.8"

services:
  webapp:
    build:
      args:
        migrate: "YES"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    command: yarn dev

  mongo:
    logging:
      driver: none
